apiVersion: v1
kind: Secret
metadata:
  name: tunesmith-secrets
type: Opaque
data:
  # These values need to be base64 encoded
  # Use: echo -n "your-actual-key" | base64
  openai-api-key: BASE64_ENCODED_OPENAI_API_KEY
  spotify-client-id: BASE64_ENCODED_SPOTIFY_CLIENT_ID
  spotify-client-secret: BASE64_ENCODED_SPOTIFY_CLIENT_SECRET
  flask-secret-key: BASE64_ENCODED_FLASK_SECRET_KEY 